dataset_path: data/commonsense/generation/commonsense_generation_ja.jsonl
few_shot_path: data/commonsense/generation/few_shot_for_commonsense-generation_ja.jsonl
generation_kwargs:
  max_new_tokens: 1024
  do_sample: true
  temperature: 0.01
  top_p: 1.0
  num_beams: 1
